site_name: Sayaki's Codex
site_description: Personal Study Library
site_author: Sayaki
site_url: https://sayakio.github.io/Codex

repo_url: https://github.com/Sayaki-qwq/Codex
repo_name: Sayaki/Codex

copyright: 'Copyright &copy; 2026 Sayaki'

theme:
  name: material
  features:
    - navigation.tabs 
    - navigation.top  
    - navigation.instant
    - search.suggest  
    - search.highlight
    - content.tab.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  favicon: 'favicon.svg'
  icon:
    logo: 'material/vpn'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

nav:
  - 首页: index.md
  - 读书笔记:
    - Calculus of Variations: 
      - Chapter I Elements of the theory: books/calculus-of-variations/chapter1-elements-of-the-theory.md
    - Pattern Recognition and Machine Learning:
      - Chapter I Introduction: books/pattern-recognition-and-machine-learning/chapter1-introduction.md  

plugins:
  - toggle-sidebar:
      theme: material
      toggle_button: all
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode:generic}}
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/extra.css

extra:
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> &copy; 2026 Sayaki'