site_name: Sayaki's Codex
site_description: Personal Learning Library
site_author: Sayaki
site_url: https://Sayakio.github.io/Codex/

repo_url: https://github.com/Sayakio/Codex
repo_name: Sayaki/Codex

copyright: 'Copyright &copy; 2026 <a href="https://github.com/Sayakio" target="_blank" rel="noopener">Sayaki</a>'

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs 
    - navigation.tracking
    - navigation.indexes
    - navigation.top  
    - search.suggest  
    - search.highlight
    - content.tab.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  favicon: 'favicon.svg'
  icon:
    logo: 'material/vpn'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

nav:
  - 首页: index.md
  - 读书笔记:
    - books/index.md
    - Calculus of Variations: 
      - Chapter I Elements of the theory: books/calculus-of-variations/chapter1-elements-of-the-theory.md
    - Pattern Recognition and Machine Learning:
      - Chapter I Introduction: books/pattern-recognition-and-machine-learning/chapter1-introduction.md 
      - Chapter II Probability Distribution: books/pattern-recognition-and-machine-learning/chapter2-probability-distribution.md
  - 论文笔记:
    - papers/index.md
    - papers/test1.md
    - papers/test2.md

markdown_extensions:
  - meta
  - md_in_html
  - toc:
      permalink: true
  - attr_list
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode:generic}}
  - pymdownx.arithmatex:
      generic: true

plugins:
  - toggle-sidebar:
      theme: material
      toggle_button: all
  - search
  - statistics:
      page_check_metadata: stats
      page_template: templates/statistics.html
  - git-revision-date-localized:
      exclude:
        - index.md

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cn.vercount.one/js     

extra_css:
  - css/extra.css

extra:
  copyright:
    author: Sayaki
    year: 2026
    license: CC BY-NC-SA 4.0
    
  analytics:
    provider: google
    property: G-2NVLQ4ZLS6

hooks:
  - hooks/build_papers_graph.py